const initialDetails = [
    {
        TABLE: 'APADV',
        TITLE: 'PAYMENT ADVICES'
    },
    {
        TABLE: 'APAGED',
        TITLE: 'AGED DOCUMENTS'
    },
    {
        TABLE: 'APBTA',
        TITLE: 'PAYMENT AND ADJUSTMENT BATCHES'
    },
    {
        TABLE: 'APCCS',
        TITLE: '1099 / CRS AMOUNTS'
    },
    {
        TABLE: 'APCLX',
        TITLE: '1099 / CPRS CODES'
    },
    {
        TABLE: 'APCMMTP',
        TITLE: 'COMMENT TYPES'
    },
    {
        TABLE: 'APDSD',
        TITLE: 'DISTRIBUTION SET DETAILS'
    },
    {
        TABLE: 'APDSH',
        TITLE: 'DISTRIBUTION SETS'
    },
    {
        TABLE: 'APGLREF',
        TITLE: 'G/L REFERENCE INTEGRATION'
    },
    {
        TABLE: 'APIBC',
        TITLE: 'INVOICE BATCHES'
    }/* 
    'APIBC: INVOICE BATCHES',
    'APIBD: INVOICE DETAILS',
    'APIBDA: INVOICE DETAIL SAGE FIXED ASSETS FIELDS',
    'APIBDO: INVOICE DETAIL OPTIONAL FIELDS',
    'APIBH: INVOICES', 
    'APIBHO: INVOICE OPTIONAL FIELDS',
    'APIBS: INVOICE PAYMENT SCHEDULES',
    'APIBT: INVOICE DETAIL COMMENTS',
    'APINTCK: INTEGRITY CHECKER',
    'APJTR: JOB COSTING TRANSACTIONS',
    'APMSG: EMAIL MESSAGES',
    'APOBL: DOCUMENTS',
    'APOBLJ: OPEN DOCUMENT DETAILS',
    'APOBLJO: OPEN DOC. DETAIL OPTIONAL FIELDS',
    'APOBLJP: DOCUMENT DETAIL PAYMENTS',
    'APOBLO: OPEN DOCUMENT OPTIONAL FIELDS',
    'APOBP: DOCUMENT PAYMENTS',
    'APOBS: DOCUMENT SCHED. PAYMENTS',
    'APOFD: OPTIONAL FIELDS',
    'APOFH: OPTIONAL FIELD LOCATIONS',
    'APP01: COMPANY OPTIONS', 
    'APP02: INVOICING OPTIONS', 
    'APP03: PAYMENT AND AGING OPTIONS',
    'APP04: INTEGRATION OPTIONS',
    'APP05: VENDOR OPTIONS',
    'APPJAID: POSTING JOURNAL GENERATED AP DETAILS',
    'APPJAIH: POSTING JOURNAL GENERATED AP ENTRIES',
    'APPJD: POSTING JOURNAL DETAILS',
    'APPJDO: POSTING JOURNAL DETAIL OPTIONAL FIELDS',
    'APPJGID: POSTING JOURNAL GENERATED GL DETAILS',
    'APPJH: POSTING JOURNAL ENTRIES',
    'APPJHO: POSTING JOURNAL ENTRY OPTIONAL FIELDS',
    'APPJS: POSTING JOURNALS',
    'APPOOP: CREATE OPEN DOCUMENT LIST',
    'APPTER: POSTING ERROR MESSAGES',
    'APPTP: PAYMENT CODES',
    'APPYM: POSTED PAYMENTS',
    'APRAS: ACCOUNT SETS',
    'APRDC: DISTRIBUTION CODES',
    'APRPD: RECURRING PAYABLE DETAILS',
    'APRPDO: RECURRING PAYABLE DETAIL FIELDS',        
    'APRPH: RECURRING PAYABLES',
    'APRPHO: RECURRING PAYABLE OPTIONAL FIELDS',
    'APRSTRT: RESTART',
    'APRTA: TERMS',
    'APRTB: TERMS PAYMENT SCHEDULE',
    'APRTG: RETAINAGE OPEN DOUCMENTS',
    'APRVL: REVALUATION DETAILS',
    'APRVLLOG: REVALUATION HISTORY',
    'APRVLO: REVALUATION OPTIONAL FIELDS',
    'APSLD: SELECTION CRITERIA DETAILS',
    'APSLH: SELECTION CRITERIA HEADER',
    'APSLHO: SELECTION CRITERIA OPT. FIELDS',
    'APSLVEN: SELECTED VENDORS',
    'APTCC: ADVANCE CREDITS',
    'APTCN: MISCELLANEOUS PAYMENTS',
    'APTCP: APPLIED PAYMENTS',
    'APTCR: PAYMENTS/ADJUSTMENTS',
    'APTCRO: PAYMENT/ADJUSTMENT OPTIONAL FIELDS',
    'APTCT: PAYMENT TAX WITHHOLDINGS',
    'APTCU: ADJUSTMENT G/L DISTRIBUTIONS',
    'APTRK: PAYMENT G/L DISTRIBUTIONS',
    'APVCM: VENDOR COMMENTS',
    'APVCMD: VENDOR COMMENT DETAILS',
    'APVEN: VENDORS',
    'APVENC: VENDOR CONTACTS',
    'APVENCF: VENDOR CONTACT FORMS',
    'APVENO: VENDOR OPTOINAL FIELD VALUES',
    'APVGR: VENDOR GROUPS',
    'APGFRO: VENDOR GROUP OPTIONAL FIELD VALUES',
    'APVGS: VENDOR GROUP STATISTICS',
    'APVNR: REMIT-TO LOCATIONS',
    'APVNRO: REMIT-TO LOCATION OPTIONAL FIELD VALUES',
    'APVSM: VENDOR STATISTICS' */
]


export default initialDetails